config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/bookings/:id/recap', to: 'bookings#recap', as: :recap
  resources :bookings,  only: [:new, :create, :show, :destroy] do
      resources :reviews, only: [:create, :new]
      resources :payments, only: :new
  end
  resources :slots, only: [:new, :create, :update, :destroy, :edit]
  resources :chatrooms, only: :show do
    resources :messages, only: [:create, :destroy]
end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :review, dependent: :destroy
  after_create :create_chatroom
  belongs_to :user
  belongs_to :slot
  has_one :chatroom, dependent: :destroy


  validates :start_time, presence: true
  validates :end_time, presence: true

  def computed_price
    (((self.end_time - self.start_time)/3600) * self.user.user_price).fractional
  end


  def display_price
    (computed_price / 100.00).to_s + ' €'
  end

  private
  def create_chatroom
    Chatroom.create(booking: self)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new

    #@dashboard = Dashboard.find(params[:dashboard_id])
    @booking = Booking.new
    authorize @booking


    @ville = params[:ville]
    @start_query = params[:start_time]
    @end_query = params[:end_time]

    if @ville.present? && @start_query.present? && @end_query.present?
      @slots = Slot.joins(:user).where("address ILIKE ?", "%#{params[:ville]}%")
      @slots.select do |slot|
        slot.start_time <= @start_query && slot.end_time >= @end_query
      end
      @available_slots = @slots.select do |slot|
        slot.available?(@start_query, @end_query)
      end
    end

    @available_slot_one = @available_slots.sample
    @reviews = []
    Review.all.map { |review| @reviews << review if review.booking.slot.user_id == @available_slot_one.user.id }
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    @reviews = Review.all
    #@dashboard = dashboard.new
    session = Stripe::Checkout::Session.create({
        payment_method_types: ['card'],
        line_items: [{
          name: @booking.slot.user.first_name,
          amount: @booking.computed_price,
          currency: 'eur',
          quantity: 1
        }],
        success_url: dashboard_url,
        cancel_url: dashboard_url
      })
      @booking.update(checkout_session_id: session.id)

  end

  def create


    @booking = Booking.new(booking_params)
    authorize @booking

    @booking.user = current_user
    @booking.task_accomplished = false
    @booking.booking_price_cents = @booking.computed_price
    if @booking.save
      redirect_to booking_path(@booking)

    else
      render :new
    end

  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, notice: 'Votre réservation a bien été annulée.'
    authorize @booking

  end

  def recap
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  private

  def booking_params

    params.require(:booking).permit(:start_time, :status, :end_time, :slot_id, :task_accomplished)

  end
end

app/views/bookings/new.html.erb
    <% if @available_slots.empty? %>
    <p>Personnne de dispo déso</p>
    <%= link_to root_path  %>
  <% else %>

 <%= link_to root_path, class: "fas fa-arrow-left" do %>
  <% end %>

<div class="flex">
  <%= cl_image_tag @available_slot_one.user.photo.key, class: "card-img" %>
  <%= cl_image_tag @available_slot_one.user.photo.key, class: "avatar-large" %>
</div>

<div class="container">

  <div class="cards-infos">
    <div class="cards-infos-left">
       <div class="rating">
          <% @available_slot_one.user.average_rating.times do %>
            <i class="fas fa-star gray-star"></i>
          <%end%>
          <% ( 5 - @available_slot_one.user.average_rating).times do %>
            <i class="far fa-star gray-star"></i>
          <%end%>
        <p><%=@available_slot_one.user.number_of_reviews%> avis</p>
      </div>
      <h2><%=@available_slot_one.user.first_name%></h2>
      <div class="cards-infos-address">
        <i class="fas fa-map-marker-alt"></i>
        <p><%=@available_slot_one.user.address%></p>
      </div>
    </div>
  <h3> <%=(@available_slot_one.user.user_price_cents)/100%>€/h</h3>
  </div>

  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Description</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Expériences</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Avis</button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="bloc-description">
        <p> <%= @available_slot_one.user.description %> </p>
      </div>
    </div>

    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div class="card-dash">
        <div class= "green">
          <%= image_tag "qualification.png", alt: "perso", class: "img-icone"%>
        </div>
        <div class="card-expe-infos-green">
          <h2> Qualification</h2>
          <p><%= @available_slot_one.user.degree %></p>
        </div>
      </div>
      <div class="card-dash">
        <div class= "green">
          <%= image_tag "experience.png", alt: "perso", class: "img-icone" %>
        </div>
        <div class="card-expe-infos-green">
          <h2>Expérience</h2>
          <p><%= @available_slot_one.user.years_of_experience %> ans </p>
        </div>
      </div>
    </div>

    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <%#= raise %>
      <% @reviews.each do |review| %>
        <div class="cards-review">
             <%= cl_image_tag review.booking.user.photo.key, class: "avatar" %>
            <div class="cards-review-content">
              <h2><%= review.booking.user.first_name%></h2>
              <p><%= review.content%></p>
            </div>
          </div>
      <% end %>
    </div>

  <div class="container-center">
    <%= simple_form_for(@booking) do |f| %>
      <input name="booking[start_time]" value="<%= @start_query %>" class="d-none">
      <input name="booking[end_time]" value="<%= @end_query %>" class="d-none">
      <%= f.input :slot_id, input_html: { value: @available_slot_one.id, class: 'd-none' }, label: false %>
        <button class="btn-green-1">
          <span class="submit">CONFIRMER</span>
          <span class="loading"><i class="fa fa-refresh"></i></span>
                  </button>
    <% end %>
    <%= link_to 'AUTRE PROFIL', new_booking_path(ville: @ville, start_time: @start_query, end_time: @end_query), class: "titleh3"%>
  <% end %>
  </div>
</div>

app/views/bookings/recap.html.erb
  <%= link_to dashboard_path, class: "fas fa-arrow-left" do %>
  <% end %>


<div class="container-center">
  <div class="top-title">
    <p>RÉCAPITULATIF</p>
  </div>
</div>

<div class="container">

  <div class="cards-recap">
   <%= cl_image_tag @booking.slot.user.photo.key, class: "avatar-carre" %>
    <div class="cards-recap-infos">
      <h2><%= @booking.slot.user.first_name %></h2>
        <div class="rating">
          <% @booking.slot.user.average_rating.times do %>
            <i class="fas fa-star gray-star"></i>
          <%end%>
          <% ( 5 - @booking.slot.user.average_rating).times do %>
            <i class="far fa-star gray-star"></i>
          <%end%>
          <p><%=@booking.slot.user.number_of_reviews%> avis</p>
          </div>
        </div>
    </div>

  <div class="champ-title">
    <p>Adresse</p>
  </div>
  <div class="champ-big-gray">
    <p><%=@booking.slot.user.address%></p>
  </div>

  <div class="champ-title">
    <p>Date</p>
  </div>

  <div class="champ-big-gray">
    <p><%= @booking.start_time.strftime("%Y %B %d")%></p>
  </div>

  <div class="container-flex">
    <div class="hour-title1">
      <p>Heure de début </p>
    </div>
    <div class="hour-title2">
      <p>Heure de fin</p>
    </div>
  </div>


  <div class="container-flex">
    <div class="champ-small-gray">
      <p><%= @booking.start_time.strftime("%H:00") %></p>
    </div>
    <div class="champ-small-gray">
      <p><%= @booking.end_time.strftime("%H:00") %></p>
    </div>
  </div>

  <div class="cards-price">
    <div class="cards-price-flex">
      <p>Prestation</p>
      <p><%=@booking.display_price %> €</p>
    </div>
    <div class="cards-price-flex">
      <p>Frais </p>
      <% @frais = 2.50 %>
      <p> <%= @frais %> € </p>
    </div>
    <div class="ligne w-100"></div>
    <div class="cards-price-flex">
      <h3>Total</h3>
      <% @total = (@frais*100 + @booking.computed_price)/100  %>
      <h3> <%= @total %> €</h3>
    </div>
  </div>

  <div class="container-center">
  <% if @booking.task_accomplished == false %>
    <div class= "btn-red">
      <%= link_to 'ANNULER', booking_path(@booking), method: :delete, data: { confirm: " Êtes-vous sûr de vouloir annuler votre réservation"}, class: 'text-danger'%>
    </div>

  <% else @booking.task_accomplished == true %>
   <div class= "btn-green">
      <%= link_to 'LAISSER UN AVIS', new_booking_review_path(@booking) %>
    </div>
  <%  end  %>
  </div>


</div>

app/views/bookings/show.html.erb
<!DOCTYPE html>
<html>


<div class= "fas fa-arrow-left" >
  <% link_to root_path %>
</div>


 <%= link_to root_path, class: "fas fa-arrow-left" do %>
  <% end %>

<div class="container-center">
  <div class="top-title">
    <p>RÉCAPITULATIF</p>
  </div>
</div>

<div class="container">

<div class="cards-recap">
 <%= cl_image_tag @booking.slot.user.photo.key, class: "avatar-carre" %>
  <div class="cards-recap-infos">
    <h2><%= @booking.slot.user.first_name %></h2>
      <div class="rating">
          <% @booking.slot.user.average_rating.times do %>
            <i class="fas fa-star gray-star"></i>
          <%end%>
          <% ( 5 - @booking.slot.user.average_rating).times do %>
            <i class="far fa-star gray-star"></i>
          <%end%>
        <p><%=@booking.slot.user.number_of_reviews%> avis</p>
      </div>
  </div>
</div>

<div class="champ-title">
  <p>Adresse</p>
</div>
<div class="champ-big-gray">
  <p><%=@booking.slot.user.address%></p>
</div>

<div class="champ-title">
  <p>Date</p>
</div>

<div class="champ-big-gray">
  <p><%= @booking.start_time.strftime("%Y %B %d")%></p>
</div>

<div class="container-flex">
  <div class="hour-title1">
    <p>Heure de début </p>
  </div>
  <div class="hour-title2">
    <p>Heure de fin</p>
  </div>
</div>


<div class="container-flex">
  <div class="champ-small-gray">
    <p><%= @booking.start_time.strftime("%H:00") %></p>
  </div>
  <div class="champ-small-gray">
    <p><%= @booking.end_time.strftime("%H:00") %></p>
  </div>
</div>

<div class="cards-price">
  <div class="cards-price-flex">
    <p>Prestation</p>
    <p><%=@booking.display_price%> €</p>
  </div>
  <div class="cards-price-flex">
    <p>Frais </p>
    <% @frais = 2.50 %>
    <p> <%= @frais %> € </p>
  </div>
  <div class="ligne w-100"></div>
  <div class="cards-price-flex">
    <h3>Total</h3>
    <% @total = (@frais*100 + @booking.computed_price)/100 %>
    <h3> <%= @total %> €</h3>
  </div>
</div>

<div class="container-center">




 <!-- <div class="container-center">
  <span<%= link_to 'PAYER', dashboard_path, class: "btn-green"  %>/span>
</div>
</div> -->
<div class="container-center">
<button id="pay" class="btn btn-green">PAYER</button>

      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @booking.checkout_session_id %>'
          });
        });
     </script>

  <%= link_to 'MODIFIER', root_path, class: "titleh3"  %>
</div>