config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/bookings/:id/recap', to: 'bookings#recap', as: :recap
  resources :bookings,  only: [:new, :create, :show, :destroy] do
      resources :reviews, only: [:create, :new]
      resources :payments, only: :new
  end
  resources :slots, only: [:new, :create, :update, :destroy, :edit]
  resources :chatrooms, only: :show do
    resources :messages, only: [:create, :destroy]
end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_components.html.erb
<div class="fond_vert">
  <h1><strong>Click & Clean </strong></h1>
      <p>Trouvez un agent d’entretien en 3 clics</p>

<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<div class="container">

  <div class="cards-price">
    <div class="cards-price-flex">
      <p>Prestation - 2h </p>
      <p>20€</p>
    </div>
    <div class="cards-price-flex">
      <p>Frais </p>
      <p>2,50€</p>
    </div>
    <div class="ligne w-100"></div>
    <div class="cards-price-flex">
      <h3>Total</h3>
      <h3>22,50€</h3>
    </div>
  </div>

  <div class="cards-infos">
    <div class="cards-infos-left">
      <div class="rating-infos">
        <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><p> 56 avis </p>
      </div>
      <h2>Paul</h2>
      <div class="cards-infos-address">
        <i class="fas fa-map-marker-alt"></i>
        <p>Marseille, France</p>
      </div>
    </div>
  <h3>10€/h</h3>
  </div>

  <div class="bloc-description">
    <p>Salut moi c’est Thierry j’adore la propreté à bientot. se en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il </p>
  </div>

<div class="container-center">
<div class="btn-green">
  <p>ENVOYER</p>
</div>

<div class="btn-white">
  <p>S'INSCRIRE</p>
</div>
</div>

<div class="champ-big">
  <p>92 E, Impasse des Cigales</p>
</div>

<div class="champ-big-gray">
  <p>92 E, Impasse des Cigales</p>
</div>

<div class="container-flex">
  <div class="champ-small">
    <p>08h00</p>
  </div>
  <div class="champ-small">
    <p>08h00</p>
  </div>
</div>

<div class="cards-recap">
  <img class="avatar-carre" alt="avatar-carre" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
  <div class="cards-recap-infos">
    <h2>Paul</h2>
      <div class="rating">
        <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><p> 56 avis </p>
      </div>
  </div>
</div>


<img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
<img class="avatar-carre-big" alt="avatar-carre-big" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
<img class="avatar-carre-small" alt="avatar-carre-small" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />

<div class="cards-review">
  <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar" />
  <div class="cards-review-content">
    <h2>Paul</h2>
    <p>Lorem ipsum dolor sit amet,adipisicing elit.Lorem ipsum dolor sit amet,adipisicing elit.Lorem ipsum dolor sit amet,adipisicing elit.</p>
  </div>
</div>

<div class="card-dash">
  <div class= "green">
    <h3>Jul <br> 16 </h3>
  </div>
  <div class="card-dash-infos">
    <h2>Paul</h2>
    <p>De 13h à 15h <br>167 rue Paradis <br>13006 Marseille </p>
  </div>
  <img class="avatar-carre-small" alt="avatar-carre-small" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
</div>

<div class="card-dash">
  <div class= "gray">
    <h3>Jul <br> 16 </h3>
  </div>
  <div class="card-dash-infos">
    <h2>Paul</h2>
    <p>De 13h à 15h <br>167 rue Paradis 13006 Marseille </p>
  </div>
</div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
      <a data-bs-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
      <a data-bs-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to root_path  do %>
            <div class= "nav-link"> <%= image_tag("Home_fond_vert.png") %></div>
            <h1>Accueil</h1>
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to image_tag("Profil_fond_vert.png"), "#", class: "nav-link" %>
          <h1>Mon profil</h1>
        </li>
        <li class="nav-item">
          <%= link_to dashboard_path  do %>
            <div class= "nav-link"><%= image_tag("Dashboard_fond_vert.png") %></div>
            <h1>Mes réservations</h1>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete  do %>
            <div class= "nav-link"><%= image_tag("Parametre_fond_vert.png") %></div>
            <h1>Se déconnecter</h1>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_bas.html.erb
<div class=" navbar-expand-sm navbar-bas justify-content-around">


  <% if controller_name == "pages" && action_name == "home"%>
      <div class= "nav-link-bas">
        <%= link_to root_path  do %>
          <%= image_tag("Home_sans_fond.png")%>
        <% end %>
      </div>
  <% else  %>
      <div class= "nav-link-bas">
        <%= link_to root_path  do %>
          <%= image_tag("home-gris.png")%>
        <% end %>
      </div>
  <% end  %>


  <% if controller_name == "pages" && action_name == "dashboard"%>
      <div class= "nav-link-bas">
        <%= link_to dashboard_path  do %>
          <%= image_tag("Dashboard_sans_fond.png")%>
        <% end %>
      </div>
  <% else %>
      <div class= "nav-link-bas">
        <%= link_to dashboard_path  do %>
          <%= image_tag("resa-gris.png")%>
        <% end %>
      </div>
  <% end  %>


  <div class= "nav-link-bas">
    <%= link_to dashboard_path  do %>
      <%= image_tag("profil-gris.png") %>
    <% end %>
  </div>


<% if user_signed_in? %>
  <% unless current_user.bookings.empty? %>
      <% if controller_name == "chatrooms" && action_name == "show"%>
          <div class= "nav-link-bas">
            <%= link_to chatroom_path(current_user.bookings.last.chatroom)  do %>
              <%= image_tag("chat-vert.png")%>
            <% end %>
          </div>
      <% else %>
          <div class= "nav-link-bas">
            <%= link_to chatroom_path(current_user.bookings.last.chatroom) do %>
              <%= image_tag("chat_gris.png")%>
            <% end %>
          </div>
      <% end  %>
  <% end %>
<% end %>
</div>