config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/bookings/:id/recap', to: 'bookings#recap', as: :recap
  resources :bookings,  only: [:new, :create, :show, :destroy] do
      resources :reviews, only: [:create, :new]
      resources :payments, only: :new
  end
  resources :slots, only: [:new, :create, :update, :destroy, :edit]
  resources :chatrooms, only: :show do
    resources :messages, only: [:create, :destroy]
end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<div class= "top-title-d">
  <p>MES RESERVATIONS</p>
</div>
<div class="container">
<div class="container-center">
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">À venir</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Passées</button>
    </li>
  </ul>
</div>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
  <% @bookings.each do |booking| %>
      <% if booking.task_accomplished == false %>

        <%= link_to recap_path(booking) do %>
          <div class="card-dash">
            <div class= "green">
              <h3><%= booking.start_time.strftime("%b")%>  <br> <%= booking.start_time.strftime("%d")%>  </h3>
            </div>
            <div class="card-expe-infos-green">
              <h2> <%= booking.slot.user.first_name%> <%= booking.slot.user.last_name%></h2>
              <p>De <%= booking.start_time.strftime("%H:00") %> à <%= booking.end_time.strftime("%H:00") %> <br> <%= booking.slot.user.address %></p>
            </div>
            <%= cl_image_tag booking.slot.user.photo.key, class: "avatar-carre-small" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <% @bookings.each do |booking| %>
      <% if booking.task_accomplished == true %>
        <%= link_to recap_path(booking) do %>
          <div class="card-dash">
            <div class= "gray">
              <h3><%= booking.start_time.strftime("%b")%>  <br> <%= booking.start_time.strftime("%d")%>  </h3>
            </div>
            <div class="card-dash-infos">
              <h2> <%= booking.slot.user.first_name%> <%= booking.slot.user.last_name%></h2>
              <p>De <%= booking.start_time.strftime("%H:00") %> à <%= booking.end_time.strftime("%H:00") %> <br> <%= booking.slot.user.address %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/pages/home.html.erb
  <div class="block-vert">
  </div>

<div class="fond-vert">
  <div class="row">
    <div class="banner">
      <%= image_tag "Perso.png", alt: "perso" , class: "img-perso"%>
      <h2>Clean-up </h2>
        <p>Trouvez un agent d'entretien en 3 clics</p>
    </div>
  </div>
</div>
<head/>

<body>
  <div class="booking-form">
    <%= form_tag new_booking_path, method: :get, :id => "home-search" do %>

              <%= text_field_tag :ville, nil,
              class: 'form-group',
              placeholder: "Ma ville" %>


              <%= datetime_field_tag :start_time, nil,
              class: 'form-group',
              value: "Date de début" %>

               <%= datetime_field_tag :end_time, nil,
              class: 'form-group',
              placeholder: 'Date de fin' %>

              <%= submit_tag '', id: 'trouver-btn', class: 'btn btn-flat-find d-none' %>

            <% end %>
            <button class="submit-button">
                <span class="pre-state-msg">RECHERCHER</span>
                <span class="current-state-msg hide">EN COURS...</span>
                <span class="done-state-msg hide" style= "margin-top: 25px">UN AGENT TROUVÉ!</span></button>
</div>